name: $name
main: io.github.krys.nextrtp.NextPlugin
version: $version
api-version: 1.20.5
author: Krysz_
description: A better option, with better performance, a better rtp.
softdepend:
  - Vault
  - PlaceholderAPI
  - MiniPlaceholders
permissions:
  nextrtp.command.*:
    children:
      nextrtp.command.reload: true
      nextrtp.command.rtp: true
      nextrtp.command.sudo: true
      nextrtp.command.world: true
      nextrtp.command.location: true

  nextrtp.command.rtp:
    default: true

  nextrtp.sign:
    default: false
  nextrtp.admin:
    children:
      nextrtp.sign: true
      nextrtp.command.*: true
      nextrtp.bypass.*: true
      nextrtp.bypass.command.*: true
  nextrtp.bypass.*:
    children:
      nextrtp.bypass.timer: true
      nextrtp.bypass.cooldown: true
      nextrtp.bypass.money: true
  nextrtp.bypass.command.*:
    children:
      nextrtp.bypass.command.world: true