name: NextRTP
main: ur.kryz.rtp.NextRTPPlugin
version: $version
api-version: 1.20
author: Krysz_
description: A plugin to add RTP configurable to your server
softdepend:
  - Vault
  - PlaceholderAPI
permissions:
  nextrtp.command.*:
    children:
      nextrtp.command.reload: true
      nextrtp.command.rtp: true
      nextrtp.command.sudo: true
      nextrtp.command.world: true
      #nextrtp.command.location: true
  nextrtp.command.rtp:
    default: true
  nextrtp.sign:
    default: false
  nextrtp.admin:
    children:
      nextrtp.sign: true
      nextrtp.command.*: true
      nextrtp.bypass.*: true
      nextrtp.world.*: true
  nextrtp.world.*:
    description: "Rtp enabled in all worlds."
  nextrtp.bypass.*:
    children:
      nextrtp.bypass.timer: true
      nextrtp.bypass.cooldown: true
      nextrtp.bypass.money: true